#
# Autogenerated by Thrift Compiler (0.21.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import thrift_classes.base.ttypes

from thrift.transport import TTransport
all_structs = []


class Transaction(object):
    """
    Attributes:
     - entityId
     - genre
     - accountType
     - pairId
     - currency
     - amount
     - freezeAmount
     - minAmount
     - subsidiaryAccount
     - description

    """


    def __init__(self, entityId=None, genre=None, accountType=None, pairId=None, currency=None, amount=None, freezeAmount=None, minAmount=None, subsidiaryAccount=None, description=None,):
        self.entityId = entityId
        self.genre = genre
        self.accountType = accountType
        self.pairId = pairId
        self.currency = currency
        self.amount = amount
        self.freezeAmount = freezeAmount
        self.minAmount = minAmount
        self.subsidiaryAccount = subsidiaryAccount
        self.description = description

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.entityId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.genre = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.accountType = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.pairId = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I32:
                    self.currency = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.amount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRING:
                    self.freezeAmount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.minAmount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.STRING:
                    self.subsidiaryAccount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.STRING:
                    self.description = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Transaction')
        if self.entityId is not None:
            oprot.writeFieldBegin('entityId', TType.I64, 1)
            oprot.writeI64(self.entityId)
            oprot.writeFieldEnd()
        if self.genre is not None:
            oprot.writeFieldBegin('genre', TType.I32, 2)
            oprot.writeI32(self.genre)
            oprot.writeFieldEnd()
        if self.accountType is not None:
            oprot.writeFieldBegin('accountType', TType.I32, 3)
            oprot.writeI32(self.accountType)
            oprot.writeFieldEnd()
        if self.pairId is not None:
            oprot.writeFieldBegin('pairId', TType.I32, 4)
            oprot.writeI32(self.pairId)
            oprot.writeFieldEnd()
        if self.currency is not None:
            oprot.writeFieldBegin('currency', TType.I32, 5)
            oprot.writeI32(self.currency)
            oprot.writeFieldEnd()
        if self.amount is not None:
            oprot.writeFieldBegin('amount', TType.STRING, 6)
            oprot.writeString(self.amount.encode('utf-8') if sys.version_info[0] == 2 else self.amount)
            oprot.writeFieldEnd()
        if self.freezeAmount is not None:
            oprot.writeFieldBegin('freezeAmount', TType.STRING, 7)
            oprot.writeString(self.freezeAmount.encode('utf-8') if sys.version_info[0] == 2 else self.freezeAmount)
            oprot.writeFieldEnd()
        if self.minAmount is not None:
            oprot.writeFieldBegin('minAmount', TType.STRING, 8)
            oprot.writeString(self.minAmount.encode('utf-8') if sys.version_info[0] == 2 else self.minAmount)
            oprot.writeFieldEnd()
        if self.subsidiaryAccount is not None:
            oprot.writeFieldBegin('subsidiaryAccount', TType.STRING, 9)
            oprot.writeString(self.subsidiaryAccount.encode('utf-8') if sys.version_info[0] == 2 else self.subsidiaryAccount)
            oprot.writeFieldEnd()
        if self.description is not None:
            oprot.writeFieldBegin('description', TType.STRING, 10)
            oprot.writeString(self.description.encode('utf-8') if sys.version_info[0] == 2 else self.description)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.entityId is None:
            raise TProtocolException(message='Required field entityId is unset!')
        if self.genre is None:
            raise TProtocolException(message='Required field genre is unset!')
        if self.accountType is None:
            raise TProtocolException(message='Required field accountType is unset!')
        if self.pairId is None:
            raise TProtocolException(message='Required field pairId is unset!')
        if self.currency is None:
            raise TProtocolException(message='Required field currency is unset!')
        if self.amount is None:
            raise TProtocolException(message='Required field amount is unset!')
        if self.freezeAmount is None:
            raise TProtocolException(message='Required field freezeAmount is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TransactionBulk(object):
    """
    Attributes:
     - uniqueId
     - timestamp
     - objectId
     - eventType
     - transactions

    """


    def __init__(self, uniqueId=None, timestamp=None, objectId=None, eventType=None, transactions=None,):
        self.uniqueId = uniqueId
        self.timestamp = timestamp
        self.objectId = objectId
        self.eventType = eventType
        self.transactions = transactions

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.uniqueId = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.timestamp = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.objectId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.eventType = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.LIST:
                    self.transactions = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = Transaction()
                        _elem5.read(iprot)
                        self.transactions.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TransactionBulk')
        if self.uniqueId is not None:
            oprot.writeFieldBegin('uniqueId', TType.STRING, 1)
            oprot.writeString(self.uniqueId.encode('utf-8') if sys.version_info[0] == 2 else self.uniqueId)
            oprot.writeFieldEnd()
        if self.timestamp is not None:
            oprot.writeFieldBegin('timestamp', TType.I64, 2)
            oprot.writeI64(self.timestamp)
            oprot.writeFieldEnd()
        if self.objectId is not None:
            oprot.writeFieldBegin('objectId', TType.I64, 3)
            oprot.writeI64(self.objectId)
            oprot.writeFieldEnd()
        if self.eventType is not None:
            oprot.writeFieldBegin('eventType', TType.STRING, 4)
            oprot.writeString(self.eventType.encode('utf-8') if sys.version_info[0] == 2 else self.eventType)
            oprot.writeFieldEnd()
        if self.transactions is not None:
            oprot.writeFieldBegin('transactions', TType.LIST, 5)
            oprot.writeListBegin(TType.STRUCT, len(self.transactions))
            for iter6 in self.transactions:
                iter6.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.uniqueId is None:
            raise TProtocolException(message='Required field uniqueId is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Transaction)
Transaction.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'entityId', None, None, ),  # 1
    (2, TType.I32, 'genre', None, None, ),  # 2
    (3, TType.I32, 'accountType', None, None, ),  # 3
    (4, TType.I32, 'pairId', None, None, ),  # 4
    (5, TType.I32, 'currency', None, None, ),  # 5
    (6, TType.STRING, 'amount', 'UTF8', None, ),  # 6
    (7, TType.STRING, 'freezeAmount', 'UTF8', None, ),  # 7
    (8, TType.STRING, 'minAmount', 'UTF8', None, ),  # 8
    (9, TType.STRING, 'subsidiaryAccount', 'UTF8', None, ),  # 9
    (10, TType.STRING, 'description', 'UTF8', None, ),  # 10
)
all_structs.append(TransactionBulk)
TransactionBulk.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'uniqueId', 'UTF8', None, ),  # 1
    (2, TType.I64, 'timestamp', None, None, ),  # 2
    (3, TType.I64, 'objectId', None, None, ),  # 3
    (4, TType.STRING, 'eventType', 'UTF8', None, ),  # 4
    (5, TType.LIST, 'transactions', (TType.STRUCT, [Transaction, None], False), None, ),  # 5
)
fix_spec(all_structs)
del all_structs
