#
# Autogenerated by Thrift Compiler (0.21.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import thrift_classes.base.ttypes

from thrift.transport import TTransport
all_structs = []


class Transaction(object):
    """
    Attributes:
     - traderId
     - genre
     - accountType
     - pairId
     - currencySymbol
     - amount
     - freezeAmount
     - minAmount

    """


    def __init__(self, traderId=None, genre=None, accountType=None, pairId=None, currencySymbol=None, amount=None, freezeAmount=None, minAmount=None,):
        self.traderId = traderId
        self.genre = genre
        self.accountType = accountType
        self.pairId = pairId
        self.currencySymbol = currencySymbol
        self.amount = amount
        self.freezeAmount = freezeAmount
        self.minAmount = minAmount

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.traderId = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.genre = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.accountType = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.pairId = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.currencySymbol = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.amount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRING:
                    self.freezeAmount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.minAmount = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Transaction')
        if self.traderId is not None:
            oprot.writeFieldBegin('traderId', TType.STRING, 1)
            oprot.writeString(self.traderId.encode('utf-8') if sys.version_info[0] == 2 else self.traderId)
            oprot.writeFieldEnd()
        if self.genre is not None:
            oprot.writeFieldBegin('genre', TType.I32, 2)
            oprot.writeI32(self.genre)
            oprot.writeFieldEnd()
        if self.accountType is not None:
            oprot.writeFieldBegin('accountType', TType.I32, 3)
            oprot.writeI32(self.accountType)
            oprot.writeFieldEnd()
        if self.pairId is not None:
            oprot.writeFieldBegin('pairId', TType.I32, 4)
            oprot.writeI32(self.pairId)
            oprot.writeFieldEnd()
        if self.currencySymbol is not None:
            oprot.writeFieldBegin('currencySymbol', TType.STRING, 5)
            oprot.writeString(self.currencySymbol.encode('utf-8') if sys.version_info[0] == 2 else self.currencySymbol)
            oprot.writeFieldEnd()
        if self.amount is not None:
            oprot.writeFieldBegin('amount', TType.STRING, 6)
            oprot.writeString(self.amount.encode('utf-8') if sys.version_info[0] == 2 else self.amount)
            oprot.writeFieldEnd()
        if self.freezeAmount is not None:
            oprot.writeFieldBegin('freezeAmount', TType.STRING, 7)
            oprot.writeString(self.freezeAmount.encode('utf-8') if sys.version_info[0] == 2 else self.freezeAmount)
            oprot.writeFieldEnd()
        if self.minAmount is not None:
            oprot.writeFieldBegin('minAmount', TType.STRING, 8)
            oprot.writeString(self.minAmount.encode('utf-8') if sys.version_info[0] == 2 else self.minAmount)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.traderId is None:
            raise TProtocolException(message='Required field traderId is unset!')
        if self.genre is None:
            raise TProtocolException(message='Required field genre is unset!')
        if self.accountType is None:
            raise TProtocolException(message='Required field accountType is unset!')
        if self.pairId is None:
            raise TProtocolException(message='Required field pairId is unset!')
        if self.currencySymbol is None:
            raise TProtocolException(message='Required field currencySymbol is unset!')
        if self.amount is None:
            raise TProtocolException(message='Required field amount is unset!')
        if self.freezeAmount is None:
            raise TProtocolException(message='Required field freezeAmount is unset!')
        if self.minAmount is None:
            raise TProtocolException(message='Required field minAmount is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TransactionBulk(object):
    """
    Attributes:
     - uniqueId
     - timestamp
     - transactions

    """


    def __init__(self, uniqueId=None, timestamp=None, transactions=None,):
        self.uniqueId = uniqueId
        self.timestamp = timestamp
        self.transactions = transactions

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.uniqueId = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.timestamp = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.LIST:
                    self.transactions = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = Transaction()
                        _elem5.read(iprot)
                        self.transactions.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TransactionBulk')
        if self.uniqueId is not None:
            oprot.writeFieldBegin('uniqueId', TType.STRING, 1)
            oprot.writeString(self.uniqueId.encode('utf-8') if sys.version_info[0] == 2 else self.uniqueId)
            oprot.writeFieldEnd()
        if self.timestamp is not None:
            oprot.writeFieldBegin('timestamp', TType.I64, 2)
            oprot.writeI64(self.timestamp)
            oprot.writeFieldEnd()
        if self.transactions is not None:
            oprot.writeFieldBegin('transactions', TType.LIST, 3)
            oprot.writeListBegin(TType.STRUCT, len(self.transactions))
            for iter6 in self.transactions:
                iter6.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.uniqueId is None:
            raise TProtocolException(message='Required field uniqueId is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Transaction)
Transaction.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'traderId', 'UTF8', None, ),  # 1
    (2, TType.I32, 'genre', None, None, ),  # 2
    (3, TType.I32, 'accountType', None, None, ),  # 3
    (4, TType.I32, 'pairId', None, None, ),  # 4
    (5, TType.STRING, 'currencySymbol', 'UTF8', None, ),  # 5
    (6, TType.STRING, 'amount', 'UTF8', None, ),  # 6
    (7, TType.STRING, 'freezeAmount', 'UTF8', None, ),  # 7
    (8, TType.STRING, 'minAmount', 'UTF8', None, ),  # 8
)
all_structs.append(TransactionBulk)
TransactionBulk.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'uniqueId', 'UTF8', None, ),  # 1
    (2, TType.I64, 'timestamp', None, None, ),  # 2
    (3, TType.LIST, 'transactions', (TType.STRUCT, [Transaction, None], False), None, ),  # 3
)
fix_spec(all_structs)
del all_structs
