# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transactions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\"\x07\n\x05\x45mpty\"1\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x7f\n\x0fTransactionBulk\x12\x10\n\x08uniqueId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x10\n\x08objectId\x18\x03 \x01(\x03\x12\x11\n\teventType\x18\x04 \x01(\t\x12\"\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x0c.Transaction\"\xbc\x01\n\x0bTransaction\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x14\n\x0c\x66reezeAmount\x18\x03 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x05 \x01(\t\x12\x19\n\x11subsidiaryAccount\x18\x06 \x01(\t\x12\x12\n\nentityType\x18\x07 \x01(\x05\x12\x11\n\tminAmount\x18\x08 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t2N\n\x12TransactionService\x12\x38\n\x11SubmitTransaction\x12\x10.TransactionBulk\x1a\x0f.StatusResponse\"\x00\x42#\n\x1f\x61vada.kedavra.grpc.transactionsP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037avada.kedavra.grpc.transactionsP\001'
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_STATUSRESPONSE']._serialized_start=31
  _globals['_STATUSRESPONSE']._serialized_end=80
  _globals['_TRANSACTIONBULK']._serialized_start=82
  _globals['_TRANSACTIONBULK']._serialized_end=209
  _globals['_TRANSACTION']._serialized_start=212
  _globals['_TRANSACTION']._serialized_end=400
  _globals['_TRANSACTIONSERVICE']._serialized_start=402
  _globals['_TRANSACTIONSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
